### ISSUE TITLE
Item to Cash Issue

### ISSUE THREAD

**Issue by Infalx** [Coffeelot/cw-trading#1]
The script works perfectly for item to item trades but when I attempts to make a item to cash trader the item is taken but no cash is given.
![Screenshot 2022-11-06 083445](https://user-images.githubusercontent.com/117589402/200183019-ac8da849-43c7-49c4-8448-9d34fa4fb47c.png)

**Comment by Coffeelot** [comment]
Hey! I think I managed to fix it. Can you try the latest code? (not a release yet)

**Comment by Infalx** [comment]
> 

Dude thank you, it works! Final question can I have a trader trade from cash to item?

**Comment by Coffeelot** [comment]
No problems! 
Currently there's no way to trade from cash. For sure something we'll look into.
